# Generated by Django 4.2.2 on 2023-06-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='full_description_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
