# Generated by Django 4.2.2 on 2023-06-21 16:55

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_full_description_item_full_description_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='full_description_photo',
            field=models.ImageField(blank=True, null=True, storage=item.models.CustomS3Boto3Storage(), upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=item.models.CustomS3Boto3Storage(), upload_to='media/'),
        ),
    ]
